config/routes.rb
Rails.application.routes.draw do

  resources :authors
  resources :novels
  resources :genres

  get "about" => "site#about"

  get "/search(.:format)" => "search#index", as: :search

  root "site#home"

end

app/models/author.rb
class Author < ActiveRecord::Base
   has_many :novels, dependent: :destroy
end

app/models/genre.rb
class Genre < ActiveRecord::Base
   has_and_belongs_to_many :novels
end

app/models/genres_novels.rb
class GenresNovels < ActiveRecord::Base
  belongs_to :genre
  belongs_to :novel
end

app/models/novel.rb
class Novel < ActiveRecord::Base
  belongs_to :author
  has_and_belongs_to_many :genres

  def self.search(query)
    where("novels.title LIKE ? OR novels.plot LIKE ?",
      "%#{query}%", "%#{query}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
     @authors = Author.all.sort_by { |author| author.name }
  end

  def show
     @author = Author.find( params[:id] )
  end

  def new
     @author = Author.new
  end

  def create
     author = Author.new( author_params )

     if author.save
        redirect_to authors_path
     else
        render 'new'
     end
  end

  def edit
     @author = Author.find( params[:id] )
  end

  def update
     @author = Author.find( params[:id] )

     if @author.update_attributes( author_params )
        redirect_to @author
     else
        render 'edit'
     end
  end

  def destroy
     @author = Author.find( params[:id] )

     @author.destroy

     redirect_to authors_path
  end

private

  def author_params
     params.require( :author ).permit( :name, :country, :bio )
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all.sort_by { |genre| genre.novels.size }.reverse
  end

  def show
     @genre = Genre.find( params[:id] )
  end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  def index
    @novels = Novel.all.sort_by { |novel| novel.year }
  end

  def show
    @novel = Novel.find( params[:id] )
  end

  def new
     @novel = Novel.new
     @novel.author_id = params[:author_id]
  end

  def create
     novel = Novel.new( novel_params )

     if novel.save
        redirect_to author_path( novel.author_id )
     else
        render new_novel_path
     end
  end

  def edit
    @novel = Novel.find( params[:id] )
  end

  def update
    @novel = Novel.find( params[:id] )

    if @novel.update_attributes( novel_params )
      redirect_to @novel
    else
      render 'edit'
    end
  end

  def destroy
    @novel = Novel.find( params[:id] )

    author_id = @novel.author_id

    @novel.destroy

    redirect_to author_path( author_id )
  end

  private

  def novel_params
    params.require( :novel ).permit( :title, :year, :cover, :plot, :author_id, genre_ids: [] )
  end


end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @novels = Novel.includes(:genres, :author).
      search(search_param)

    respond_to do |format|
      format.html
      format.json { render json: @novels }
    end
  end

  private
    def search_param
      params.require(:query)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>

    <div class="form-group">
       <%= f.label :name %>
       <%= f.text_field :name, class: "form-control", placeholder: ". . ." %>
    </div>

    <div class="form-group">
       <%= f.label :country %>
       <%= f.text_field :country, class: "form-control", placeholder: ". . ."   %>
    </div>

    <div class="form-group">
       <%= f.label :bio %>
       <%= f.text_area :bio, class: "form-control", rows: 10  %>
    </div>

    <%= f.submit (@author.new_record? ? "Create" : "Update"), class: "form-control btn-primary" %>

<% end %>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= render "form" %>

app/views/authors/index.html.erb
<h1>Authors <%= link_to "New Author", new_author_path, class: "btn btn-default", style: "float: right" %></h1>

<% @authors.each do |author| %>
    <p><%= link_to author.name, author %></p>
<% end %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render "form" %>

app/views/authors/show.html.erb
<h1>
   <%= @author.name %>
   <%= link_to "Delete", author_path( @author ), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default", style: "float: right" %>
   <%= link_to "Edit", edit_author_path( @author ), class: "btn btn-default", style: "float: right" %>
</h1>

<h3><%= @author.country %></h3>

<p><%= simple_format @author.bio %></p>

<%= link_to "New Novel", new_novel_path( author_id: @author.id ), class: "btn btn-default", style: "float: right" %></h2>

<% novels = @author.novels.sort_by { |novel| novel.year } %>

<%= render novels, hide_author: true %>

app/views/genres/index.html.erb
<h1>Genres</h1>

<div>
   <% @genres.each do |genre| %>
       <%= link_to "#{genre.name} • #{genre.novels.size}", genre, class: "btn btn-primary" %>
   <% end %>
</div>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>

<%= render @genre.novels %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
   <div class="container-fluid">

      <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         </button>
         <%= link_to "Novad", root_path, class: "navbar-brand" %>
      </div>

      <div id="navbar" class="navbar-collapse collapse">
         <ul class="nav navbar-nav">
            <li><%= link_to "Authors", authors_path %></li>
            <li><%= link_to "Novels", novels_path %></li>
            <li><%= link_to "Genres", genres_path %></li>
         </ul>
         <%= form_tag search_path, method: :get, class: "navbar-form navbar-left", role: "search", id: "searchForm" do %>
            <div class="form-group">
              <%= search_field_tag :query, params[:search], class: "form-control", placeholder: "Search novels..." %>
            </div>
         <% end %>
         <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", about_path %></li>
         </ul>
      </div>

   </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Novad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div id="main" class="container-fluid">
   <%= render "layouts/nav" %>

   <%= yield %>
</div>

</body>
</html>

app/views/novels/_form.html.erb
<%= form_for @novel do |f| %>

    <%= f.hidden_field :author_id, :value => @novel.author.id%>

    <div class="form-group">
       <%= f.label :title %>
       <%= f.text_field :title, class: "form-control", placeholder: ". . ." %>
    </div>

    <div class="form-group">
       <%= f.label :year %>
       <%= f.text_field :year, class: "form-control", placeholder: ". . ."   %>
    </div>

    <div class="form-group">
       <%= f.label :cover %>
       <%= f.text_field :cover, class: "form-control", placeholder: "url . . ."   %>
    </div>

    <div class="form-group">
       <%= f.label :plot %>
       <%= f.text_area :plot, class: "form-control", rows: 6  %>
    </div>

    <div class="form-group">
       <%= f.label :genres, :class => "control-label" %>
       <div>
          <% genres = Genre.all.map{|t| [t.name, t.id]}.sort %>
          <%= f.select :genre_ids, genres, { class: "form-control", prompt: true }, { multiple: true, size: 10 } %>
          <p class="help-block">Select multiple with Ctrl</p>
       </div>
    </div>

    <%= f.submit (@novel.new_record? ? "Create" : "Update"), class: "form-control btn-primary" %>

<% end %>

app/views/novels/_novel.html.erb
<div class="novel-item">

   <div class="inline cover">
      <img class="small-cover" src="<%= novel.cover %>"/>
   </div>

   <div class="inline details">

      <h3><%= link_to novel.title, novel %></h3>

      <% if !defined?(hide_author) || !hide_author %>
          <h4><%= link_to novel.author.name, novel.author %></h4>
      <% end %>

      <p><%= novel.year %></p>
      <p><%= novel.plot %></p>

      <p>
         <% novel.genres.each do |genre| %>
             <%= link_to "#{genre.name}", genre, class: "btn btn-primary btn-xs" %>
         <% end %>
      </p>

   </div>

</div>

app/views/novels/edit.html.erb
<h1>Edit Novel by <%= @novel.author.name %></h1>

<%= render "form" %>

app/views/novels/index.html.erb
<h1>Novels</h1>

<%= render @novels %>

app/views/novels/new.html.erb
<h1>New Novel by <%= @novel.author.name %></h1>

<%= render "form" %>

app/views/novels/show.html.erb
<h1>
   <%= @novel.title %>
   <%= link_to "Delete", novel_path( @novel ), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default", style: "float: right" %>
   <%= link_to "Edit", edit_novel_path( @novel ), class: "btn btn-default", style: "float: right" %>
</h1>

<h3><%= link_to @novel.author.name, @novel.author %> </h3>

<p><%= @novel.year %></p>
<p><%= @novel.plot %></p>

<p>
   <% @novel.genres.each do |genre| %>
       <%= link_to "#{genre.name}", genre, class: "btn btn-primary btn-xs" %>
   <% end %>
</p>

<img class="cover" src="<%= @novel.cover %>"/>

app/views/search/index.html.erb
<h1>Search results for "<%= params[:search] %>"</h1>

<%= render @novels %>

app/views/site/about.html.erb
<h1>Novad</h1>

<p>Celebrating literature with Novels by Authors.</p>

app/views/site/home.html.erb
<h1>Novad</h1>

<a href="<%= authors_path %>"><div class="nav-box authors"><h2>Authors</h2></div>'</a>
<a href="<%= novels_path %>"><div class="nav-box novels"><h2>Novels</h2></div>'</a>
<a href="<%= genres_path %>"><div class="nav-box genres"><h2>Genres</h2></div>'</a>